services:
  oe:
    build : .
    container_name: "oe"
    tty: true
    stdin_open: true
    environment:
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
    volumes:
      - ./work:/work
    extra_hosts:
      - "host.docker.internal:host-gateway"